"""add status to users

Revision ID: 027eb37ba5d6
Revises: c31edda46efd
Create Date: 2026-07-10 12:50:30.333249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027eb37ba5d6'
down_revision = 'c31edda46efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
